### ISSUE TITLE
类似var _ PeerPicker = (*HTTPPool)(nil)这种设计目的是什么

### ISSUE THREAD

**Issue by catwithtudou** [geektutu/7days-golang#10]
首先感谢博主能写出这么好的文章，受益匪浅
然后就是在GeeCache中我看到有类似于
var _ PeerPicker = (*HTTPPool)(nil)
和
var _ PeerGetter = (*httpGetter)(nil)
请问这种设计的意义是什么，我把这一行代码去了也并没有看到报错，有点疑惑，向博主请教

**Comment by geektutu** [comment]
很细心~ 这是确保接口被实现常用的方式。即利用强制类型转换，确保 struct HTTPPool 实现了接口 PeerPicker。这样 IDE 和编译期间就可以检查，而不是等到使用的时候。

**Comment by catwithtudou** [comment]
谢谢博主

**Comment by yoursNicholas** [comment]
能不能拉一个微信群一起讨论一下啊。版主拉一下我 微信号 ：xxx_xxxu

**Comment by squallsyttt** [comment]
关于 var _ interface = (*STRUCT)(nil) 这种声明 还可以配合这边深入了解下 http://soiiy.com/index.php/go/13207.html

**Comment by yinhuanyi** [comment]
博主视乎喜欢空指针，可能我更喜欢这样验证自定义类型实现接口的方式，如下：
```
// 验证httpGetter是否实现了PeerGetter接口
var _ PeerGetter = &httpGetter{}
```

在gin的routergroup.go源码中，也有类似的验证写法
```
type IRouter interface{ ... }
...
...
type RouterGroup struct { ... }
...
var _ IRouter = &RouterGroup{} 
```

**Comment by ilaziness** [comment]
@geektutu 什么情况下会定义了结构体，没实现对应接口编译不会报错呢？
我看了简明教程里面的例子，是结构体没有使用的的情况，如果我使用了，那编译就会报错了。
定了一个结构体，而不使用，这种情况感觉很少呀。
一般传参，函数参数类型都是接口类型，如果传的参数没实现接口直接就会报错了。
