### ISSUE TITLE
小白求问 缓存day2不加锁的话 会出现什么问题呀

### ISSUE THREAD

**Issue by wfnuser** [geektutu/7days-golang#11]
![image](https://user-images.githubusercontent.com/8191686/77255410-2afdcf80-6ca2-11ea-8c0f-2af5702a3cd5.png)
就是类似框里的代码会被打乱执行顺序吗，好像其实影响也不是特别大？

因为如果put和get如果外层逻辑上不加控制的话  也不太能保证get读到的值是在put之前还是put之后的吗？ 我在想测试用例里加一些体现加锁不加锁表现上区别的是不是更容易理解点

**Comment by wfnuser** [comment]
哦 是不是不加锁的话 会出现链表操作报错之类的，比如已经在另一次put操作里把内存delete了？

**Comment by geektutu** [comment]
@wfnuser 对于任意的不支持并发操作的数据结构，比如 map，链表等，并发读写时是需要加锁操作的。你举的例子是对的，可能出现 put 前被 delete，导致程序报错退出。比如下面这个例子，并发修改`m[1]`，会导致 fatal error。

```go
func main() {
	var m = make(map[int]int)
	for i := 0; i < 10000; i++ {
		go func() { m[1] = 1 }()
	}
	time.Sleep(5000)
}
```

**Comment by wfnuser** [comment]
哈哈哈 谢谢大佬！
