### ISSUE TITLE
前缀树名称应该是 trie-tree

### ISSUE THREAD

**Issue by Lobshunter86** [geektutu/7days-golang#13]
目前文章里用的是 `tire-tree`，i 和 r 的顺序反了

博主写的很好，赞

**Comment by geektutu** [comment]
感谢你的认可，之前有童鞋评论了，统一改过一次，我没找到没改过来的地方，可能是浏览器缓存了网页？

**Comment by Lobshunter86** [comment]
我拉最新的仓库全局搜索了下：在这个几个地方是用的 tire

`README.md`: line 21, line 73
`gee-web/README.md`: line 15
`gee-web/doc/gee.md`: line 68

**Comment by geektutu** [comment]
感谢，已经修复。博客24小时后会自动更新。
