### ISSUE TITLE
第6天的代码，解析css文件，浏览器看到的内容和css文件内容不一致？

### ISSUE THREAD

**Issue by dafa168** [geektutu/7days-golang#22]
golang版本 1.14.10  .

test.css 文件内容是： 
```
body{background-color: aquamarine}
```

浏览器解析出来的css内容是：  {"filepath":"css/test.css"}

**Comment by geektutu** [comment]
可以贴一下你的 `main.go` 么， filepath 是内部实现的逻辑，内部解析出来的参数。你可以直接运行day6 中的 `main.go` 看看有没有问题。

**Comment by dafa168** [comment]
嗯嗯， day6的代码是没问题的，正常加载渲染，我先检查下main.go .
