### ISSUE TITLE
gee-rpc day1 通信过程

### ISSUE THREAD

**Issue by hanxuanliang** [geektutu/7days-golang#25]
有点不懂的是：GobType中为什么要使用json做解码编码？
或者说为什么直接默认使用JsonType？
感觉形式上有点不统一。

**Comment by geektutu** [comment]
在协议协商之前，并不知道后面的内容需要什么方式来解码。所以协议协商需要用双方约定且理解的格式。比如约定第1-4个字节表示方法的长度，第5个字节表示编码类型。第6到9字节表示报文长度等等，然后后面紧跟n个字节的报文。后面n个字节的报文需要用第5个字节指定的方式解码。正常实现协议协商的代码过于繁琐了，所以就用json简化了，不是正式的实现方式，这个地方只是表示正式报文读取前，需要有个协议协商的过程。

**Comment by hanxuanliang** [comment]
哦哦，明白。那意思就是说，代码里面指定使用 JsonType 也是一样的，这里只是表示有这么一个type对应一种解析格式而已。

**Comment by geektutu** [comment]
@hanxuanliang 协议协商给了客户端一定的自主权，可以动态协商一些方式。比如报文是否序列化了，是否压缩了，是否加密了。客户端代码可以自由选择这些方式，协商过程中告诉服务端就成。

**Comment by hanxuanliang** [comment]
好的，很感谢大佬解答。先继续把后面跟完，返回来再看应该会清晰些

**Comment by geektutu** [comment]
@hanxuanliang 这一部分为了简单，实现得很粗糙。你看到后面的使用，就能理解协议协商的意义了。这一部分，rpcx 直接解析的字节流，你也可以对照着其他成熟的开源框架一起看~

**Comment by hanxuanliang** [comment]
> @hanxuanliang 这一部分为了简单，实现得很粗糙。你看到后面的使用，就能理解协议协商的意义了。这一部分，rpcx 直接解析的字节流，你也可以对照着其他成熟的开源框架一起看~

可以的，很感谢大佬。确实要把全局看完。
