### ISSUE TITLE
syscall/js报错

### ISSUE THREAD

**Issue by sxy88** [geektutu/7days-golang#28]
额，我用的goland在跑hello-world里的main.go，报了这个错，我搜了一下需要修改GOOS和GOARCH，但是没有搜到怎么修改这两个变量，求解决。
package command-line-arguments
	imports syscall/js: build constraints exclude all Go files in D:\Go\src\syscall\js

**Comment by geektutu** [comment]
go build 编译时设置的环境变量。例如 GOOS=linux GOARCH=arm64 go build .
