### ISSUE TITLE
如果能出个 fasthttp 库的实现就更好了！

### ISSUE THREAD

**Issue by leffss** [geektutu/7days-golang#6]
如果能出个 fasthttp 库的实现就更好了！

**Comment by xsymphony** [comment]
可以关注下[fin](https://github.com/xsymphony/fin)这个库，基于fasthttp实现gin风格的http框架。
总体来说，实现思路很像7days-golang。

**Comment by leffss** [comment]
> 可以关注下[fin](https://github.com/xsymphony/fin)这个库，基于fasthttp实现gin风格的http框架。
> 总体来说，实现思路很像7days-golang。

我去看看学习一下，谢谢！

**Comment by geektutu** [comment]
fasthttp 的实现性能解析这一块比较复杂，性能提高主要是一些协程的复用。我有想过写，不过代码量比较大，且比较枯燥。

最近打算写的系列是，关于分布式缓存的，模拟 memcached 的实现，最近的 [GO RPC](https://geektutu.com/post/quick-go-rpc.html) 和 [GO PROTOBUF](https://geektutu.com/post/quick-go-protobuf.html) 正在为这个新系列铺铺路~

**Comment by leffss** [comment]
> fasthttp 的实现协议解析这一块比较复杂，性能提高主要是一些协程的复用。我有想过写，不过代码量比较大，且比较枯燥。
> 
> 最近打算写的系列是，关于分布式缓存的，模拟 memcached 的实现，最近的 [GO RPC](https://geektutu.com/post/quick-go-rpc.html) 和 [GO PROTOBUF](https://geektutu.com/post/quick-go-protobuf.html) 正在为这个新系列铺铺路~

为什么 memcached ， 模拟 redis 不是更好？期待你的教程！！！

**Comment by geektutu** [comment]
@leffss redis 代码量也太大，不仅是高速缓存，还有持久化等特性。

相对来说，[go版本的memcached](https://github.com/golang/groupcache) ，特性少，但涉及的点比较多：

- 分布式节点通信
- LRU 缓存策略
- 哈希一致性
- 预防惊群效应
- ...

千行左右的代码，这些特性都自己实现下，很适合写成七天的教程。

**Comment by leffss** [comment]
> fasthttp 的实现协议解析这一块比较复杂，性能提高主要是一些协程的复用。我有想过写，不过代码量比较大，且比较枯燥。
> 
> 最近打算写的系列是，关于分布式缓存的，模拟 memcached 的实现，最近的 [GO RPC](https://geektutu.com/post/quick-go-rpc.html) 和 [GO PROTOBUF](https://geektutu.com/post/quick-go-protobuf.html) 正在为这个新系列铺铺路~

我已经在你的基础上改了一个 fasthttp 的版本，还改了路由，可以支持正则，感觉没变多复杂呢。还是说我没理解透彻

**Comment by geektutu** [comment]
那应该是我理解错了，我理解成实现一个 fasthttp ，而不是基于 fasthttp 实现 web 框架。

**Comment by leffss** [comment]
> 那应该是我理解错了，我理解成实现一个 fasthttp ，而不是基于 fasthttp 实现 web 框架。

大佬，想问下，怎么测试你写的这个框架性能呢？和gin，beego，iris等主流框架性能对比到底如何呢？

**Comment by shlinym** [comment]
> > 那应该是我理解错了，我理解成实现一个 fasthttp ，而不是基于 fasthttp 实现 web 框架。
> 
> 大佬，想问下，怎么测试你写的这个框架性能呢？和gin，beego，iris等主流框架性能对比到底如何呢？

可以参考这个repo，https://github.com/julienschmidt/go-http-routing-benchmark

加入自定义的web框架，go的大部分主流web框架在上面都有测试结果，测完可以横向比较
