### ISSUE TITLE
在模糊匹配下再次插入节点到同样树高，会被替换掉 handler

### ISSUE THREAD

**Issue by AcidGo** [geektutu/7days-golang#8]
https://github.com/geektutu/7days-golang/blob/398679493db818265551707db70969a0e9e64529/gee-web/day3-router/gee/trie.go#L27

maybe:
```go
    if child == nil || child.isWild {
```

**Comment by AcidGo** [comment]
routers:
  GET "/a/*"  F1
  GET "/a/g" F2
--> GET "/a/*" F2

**Comment by geektutu** [comment]
@AcidGo 你说的是对的，在第一个通配，第二个是确定值的情况下，会被替换，没有做冲突检查，例如：

```go
r.addRoute("GET", "/hello/:name", nil)
r.addRoute("GET", "/hello/c", nil)
```

但如果先把`hello/c` 放在前面，`helle/:name` 放在后面则不会有这个问题。

修改成 `if child == nil || child.isWild` 是不行的，匹配时是按照顺序匹配的，匹配到通配，就不会匹配后面的节点，相当于在树中添加了一个无用节点。

**Comment by AcidGo** [comment]
@geektutu 好的。🤝

**Comment by cookieY** [comment]
@geektutu 请教下如何实现类似的冲突检查呢,是否可以提供下思路  谢谢
