### ISSUE TITLE
请教：这个for循环中加使用go开协程，会不会不停去创建无数多的goroutine?

### ISSUE THREAD

**Issue by zackzhangkai** [geektutu/7days-golang#82]
```golang
// Accept accepts connections on the listener and serves requests
// for each incoming connection.
func (server *Server) Accept(lis net.Listener) {
	for {
		conn, err := lis.Accept()
		if err != nil {
			log.Println("rpc server: accept error:", err)
			return
		}
               // 这里有问题：这里会不会不停创建goroutine?
		go server.ServeConn(conn)
	}
}
```
https://github.com/geektutu/7days-golang/blob/cf3644382101dc13e7fd92e8f5c66cabc51bcd3b/gee-rpc/day1-codec/server.go#L143

**Comment by Aj002Th** [comment]
`conn, err := lis.Accept()` 是阻塞式的，当有一个连接进入时才会继续往下执行，到 `go server.ServeConn(conn) `会对每一个需要处理的链接对应创建一个协程来负责每个连接后续的处理逻辑，处理结束后对应的协程也会退出。如果有连接不断进入，`go server.ServeConn(conn)` 就会不断创建 goroutine 来处理每个连接。

**Comment by zackzhangkai** [comment]
> `conn, err := lis.Accept()` 是阻塞式的，当有一个连接进入时才会继续往下执行，到 `go server.ServeConn(conn) `会对每一个需要处理的链接对应创建一个协程来负责每个连接后续的处理逻辑，处理结束后对应的协程也会退出。如果有连接不断进入，`go server.ServeConn(conn)` 就会不断创建 goroutine 来处理每个连接。

Got it! 感谢
