### ISSUE TITLE
为什么cache需要设计成自动回源的？

### ISSUE THREAD

**Issue by Ehco1996** [geektutu/7days-golang#9]
你好，我最近在看geeCache的实现，有些不明白地方想请教一下
```go
// Get value for a key from cache
func (g *Group) Get(key string) (ByteView, error) {
	if key == "" {
		return ByteView{}, fmt.Errorf("key is required")
	}

	if v, ok := g.mainCache.get(key); ok {
		log.Println("[GeeCache] hit")
		return v, nil
	}

	return g.load(key)
}
```

比如这段函数的末尾,在cache未命中的情况下，会自己fallback去load缓存

我没有理解这里的逻辑，为什么缓存需要自己去fallbak？难道不应该直接返回未命中么？
如果涉及成这样，那缓存岂不是永远是命中的？

**Comment by geektutu** [comment]
@Ehco1996 

回源策略有很多种，这只是一种实现，调用时用户不感知。有些还会支持用户主动向缓存中新增数据或更新数据。

另外缓存的作用，还取决于你的业务是如何抽象和分层的，即如何看待`源`。GeeCache 对用户来说就是`源`，用户只关心使用 `key` 能否取到对应的 `Value`，不关心 GeeCache 从内存中获取的，还是从DB中获取的。

或者再从另外一个角度看，如果缓存返回未命中，业务代码就需要自己从真正的 `源` 获取，再添加进缓存，那作用和自动回源是一样的，一万处调用缓存的地方就得写一万遍回源，在缓存处实现只需要1次。

GeeCache 只实现了非常少的功能，如果你有时间，还推荐看一看 Google Guava Cache 的设计，是 Java 语言的单机缓存，除了自动回源，还包含了定时失效、主动触发更新等功能。

**Comment by Ehco1996** [comment]
谢谢回答，我理解了

一开始我有这样的疑问是因为我下意识的把 `geecache`当成了类似redis的内存数据库
所以当用户的get到空值得时候，我的第一反应是应该返回空，而不是fallbak到下层去拿数据。

但实际上作为cache来看话，自动回源就是一个很合理的操作了
